export enum ServiceBarberEnum {
  CorteMilitarComBarba = 'Corte Militar com Barba',
  CorteDegradê = 'Corte Degradê',
  CorteSimples = 'Corte Simples',
  CorteInfantil = 'Corte Infantil',
  BarbaAparada = 'Barba Aparada',
  BarbaComModelagem = 'Barba com Modelagem',
  Sobrancelha = 'Sobrancelha',
  CorteETratamentoCapilar = 'Corte e Tratamento Capilar',
  CorteComPigmentação = 'Corte com Pigmentação',
  BarbaComHidratação = 'Barba com Hidratação',
  CorteEBarbaComMassagem = 'Corte e Barba com Massagem',
  TratamentoParaCalvície = 'Tratamento para Calvície',
  CorteComRelaxamento = 'Corte com Relaxamento',
  CorteDegradêComPigmentação = 'Corte Degradê com Pigmentação',
  CorteComSelagem = 'Corte com Selagem',
  CorteMilitar = 'Corte Militar',
}